DROP DATABASE IF EXISTS Pubs;
CREATE DATABASE IF NOT EXISTS Pubs;
USE Pubs;

CREATE TABLE IF NOT EXISTS EMPLEADOS(
DNI_EMPLEADO VARCHAR(20),
NOMBRE VARCHAR(100) NOT NULL,
DOMICILIO VARCHAR (100),
PRIMARY KEY (DNI_EMPLEADO)
);

INSERT INTO EMPLEADOS (DNI_EMPLEADO, NOMBRE, DOMICILIO)
VALUES ('12678A', 'Juan Pérez', 'Calle Ficticia 123'),
('12679A', 'JAVIER CARRILLO', 'Calle ANCHA 6');

CREATE TABLE IF NOT EXISTS PUB_EMPLEADO(
COD_PUB INT AUTO_INCREMENT,
FUNCION VARCHAR(100) NOT NULL,
DNI_EMPLEADO VARCHAR(20) NOT NULL,
FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADOS(DNI_EMPLEADO),
CHECK (FUNCION IN ('CAMARERO','SEGURIDAD','LIMPIEZA')),
PRIMARY KEY (COD_PUB)
);

INSERT INTO PUB_EMPLEADO (DNI_EMPLEADO, FUNCION)
VALUES('12678A','CAMARERO'),
('12679A','SEGURIDAD');

CREATE TABLE IF NOT EXISTS EXISTENCIAS(
COD_ARTICULO INT  PRIMARY KEY,
NOMBRE VARCHAR (100) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO INT NOT NULL,
COD_PUB INT NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES PUB_EMPLEADO(COD_PUB)
);

INSERT INTO EXISTENCIAS (COD_ARTICULO, NOMBRE, CANTIDAD, PRECIO,COD_PUB)
VALUES (3242, 'JAVIER CARRILLO', 5,10,1);

CREATE TABLE IF NOT EXISTS LOCALIDAD(
COD_LOCALIDAD INT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL
);

INSERT INTO LOCALIDAD (COD_LOCALIDAD,NOMBRE)
VALUES (1234,'PALMA DEL RIO');

CREATE TABLE IF NOT EXISTS PUB(
COD_PUB INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR (100) NOT NULL,
LICENCIA_FISCAL VARCHAR(100) NOT NULL,
DOMICILIO VARCHAR(100),
FECHA_APERTURA DATE NOT NULL,
HORARIO VARCHAR (4) NOT NULL,
CHECK (HORARIO IN ('HOR1','HOR2','HOR3')),
COD_LOCALIDAD INT NOT NULL,
FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD (COD_LOCALIDAD)
);

INSERT INTO PUB (NOMBRE,LICENCIA_FISCAL,DOMICILIO,FECHA_APERTURA,HORARIO,COD_LOCALIDAD)
VALUES ( 'LOCO','MENTIRA','MI CASA','2025-01-01','HOR1',1234);

SET @last_cod_pub = LAST_INSERT_ID();

CREATE TABLE IF NOT EXISTS TITULAR(
DNI_TITULAR VARCHAR (20) PRIMARY KEY,
NOMBRE VARCHAR (100) NOT NULL,
DOMICILIO VARCHAR(100),
COD_PUB INT NOT NULL,
FOREIGN KEY (COD_PUB) REFERENCES PUB (COD_PUB)
);

INSERT INTO TITULAR (DNI_TITULAR,NOMBRE,DOMICILIO,COD_PUB)
VALUES ('12679B','JAVIER',"MI CASA",@last_cod_pub);

