DROP DATABASE IF EXISTS GestionAcademica;
CREATE DATABASE IF NOT EXISTS GestionAcademica;
USE GestionAcademica;

CREATE TABLE IF NOT EXISTS ESTUDIANTES(
ID_ESTUDIANTE VARCHAR(10) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
DIRECCION VARCHAR(100),
TELEFONO VARCHAR(15),
EMAIL VARCHAR(50)
);

INSERT INTO ESTUDIANTES (ID_ESTUDIANTE,NOMBRE,DIRECCION,TELEFONO,EMAIL)
VALUES ('232313','JAVI','CALLE','642985372','CARRILO');

CREATE TABLE IF NOT EXISTS CURSOS(
ID_CURSO VARCHAR(10) PRIMARY KEY NOT NULL,
NOMBRE_CURSO VARCHAR(100),
DESCRIPCION TEXT,
DURACION INT
);

INSERT INTO CURSOS (ID_CURSO,NOMBRE_CURSO,DESCRIPCION,DURACION)
VALUES ('112233','FUCK CROISSAN','CURSO PARA HACERSE MILLONARIO',20);


CREATE TABLE IF NOT EXISTS INSCRIPCIONES(
ID_INSCRIPCION VARCHAR(10) PRIMARY KEY NOT NULL,
ID_ESTUDIANTE VARCHAR(10),
FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
ID_CURSO VARCHAR(10), 
FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO),
FECHA_INSCRIPCION DATE
);

INSERT INTO INSCRIPCIONES (ID_INSCRIPCION,ID_ESTUDIANTE,ID_CURSO,FECHA_INSCRIPCION)
VALUES ('77777','232313','112233','2020-03-19');


CREATE TABLE IF NOT EXISTS CALIFICACIONES(
ID_CALIFICACIONES VARCHAR(10) PRIMARY KEY NOT NULL,
ID_INSCRIPCION VARCHAR(10),
FOREIGN KEY (ID_INSCRIPCION) REFERENCES INSCRIPCIONES (ID_INSCRIPCION),
CALIFICACIONES DECIMAL(5,2),
FECHA_CALIFICACION DATE
);

INSERT INTO CALIFICACIONES (ID_CALIFICACIONES,ID_INSCRIPCION,CALIFICACIONES,FECHA_CALIFICACION)
VALUES ('1234','77777', 8.3, '2019-01-01');


