DROP DATABASE IF EXISTS DBZ_Ejercicio_Calculos;
CREATE DATABASE IF NOT EXISTS DBZ_Ejercicio_Calculos;
USE DBZ_Ejercicio_Calculos;

CREATE TABLE IF NOT EXISTS GUERRERO(
ID_GUERRERO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
RAZA VARCHAR(20),
NIVEL_PODER INT,
CANTIDAD_TRANSFORMACIONES INT
);

INSERT INTO GUERRERO(ID_GUERRERO,NOMBRE,RAZA,NIVEL_PODER,CANTIDAD_TRANSFORMACIONES)
VALUES 
(1,'GOKU','SAIYAN',9000,6),
(2,'VEGETA','SAIYAN',8500,4),
(3,'GOHAN','SAIYAN-MESTIZO',8000,4),
(4,'PICCOLO','NAMEKIANO',7000,1),
(5,'TRUNKS','SAIYAN',7500,2),
(6,'FREEZER','EMPERADOR DEL MAL',10000,5),
(7,'CELL','BIO-ANDROIDE',8500,3),
(8,'MAJIN BUU','MAJIN',8000,3),
(9,'GOTEN','SAIYAN',600,1),
(10,'KRILLIN','HUMANO',500,0);

SELECT NOMBRE,NIVEL_PODER
FROM GUERRERO
WHERE NIVEL_PODER > 9000;

SELECT NOMBRE,CANTIDAD_TRANSFORMACIONES
FROM GUERRERO
WHERE CANTIDAD_TRANSFORMACIONES <= 3;


SELECT NIVEL_PODER * CANTIDAD_TRANSFORMACIONES
FROM GUERRERO;

SELECT NOMBRE,NIVEL_PODER,CANTIDAD_TRANSFORMACIONES,
    CASE
         WHEN nombre = 'Piccolo' THEN 'Orange_Piccolo'
           WHEN nombre = 'Freezer' THEN 'Black_Freezer'
           WHEN raza = 'Saiyan' AND cantidad_transformaciones > 0 THEN '¡Super Saiyan!'
           WHEN cantidad_transformaciones = 0 THEN 'Sin transformaciones'
           ELSE 'Transformado'
        END AS estado_transformacion
    FROM GUERRERO;    