DROP DATABASE IF EXISTS Guerreros;
CREATE DATABASE IF NOT EXISTS Guerreros;
USE Guerreros;

CREATE TABLE IF NOT EXISTS GUERRERO(
ID_GUERRERO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50),
RAZA VARCHAR(20),
NIVEL_PODER INT
);

INSERT INTO GUERRERO(ID_GUERRERO,NOMBRE,RAZA,NIVEL_PODER)
VALUES 
(1,'GOKU','SAIYAN',9500),
(2,'VEGETA','SAIYAN',9200),
(3,'GOHAN','SAIYAN-MESTIZO',8700),
(4,'PICCOLO','NAMEK',7500),
(5,'KRILIN','HUMANO',400),
(6,'YAMCHA','HUMANO',NULL);

SELECT NOMBRE
FROM GUERRERO
WHERE NIVEL_PODER IS NULL;

SELECT NOMBRE, NIVEL_PODER
FROM GUERRERO
WHERE NIVEL_PODER <> 9500;


SELECT NOMBRE, NIVEL_PODER
FROM GUERRERO
WHERE RAZA = 'Saiyan' OR RAZA = 'Namek' AND NIVEL_PODER > 8000;