DROP DATABASE IF EXISTS Talleres;
CREATE DATABASE IF NOT EXISTS Talleres;
USE Talleres;

CREATE TABLE IF NOT EXISTS COCHES(
    MAT VARCHAR(8) PRIMARY KEY,
    MARCA VARCHAR(15),
    AN_FAB INT CHECK (AN_FAB BETWEEN 10 AND 99)
);
INSERT INTO COCHES (MAT, MARCA, AN_FAB)
VALUES ('131233','MUSTAN',25);

CREATE TABLE IF NOT EXISTS MECANICOS(
DNI VARCHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(15),
PUESTO VARCHAR(15),
PARCIAL VARCHAR(1)
);

CREATE TABLE IF NOT EXISTS TRABAJOS(
MAT VARCHAR(8),
FOREIGN KEY (MAT) REFERENCES COCHES (MAT),
DNI VARCHAR(9),
FOREIGN KEY (DNI) REFERENCES MECANICOS (DNI),
HORAS DECIMAL CHECK (HORAS > 0.5),
FECHA_REP DATE
);

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR (50),
TELEFONO VARCHAR (15)
);

CREATE TABLE IF NOT EXISTS PIEZAS(
ID_PIEZA VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(50),
PRECIO DECIMAL
);

CREATE TABLE IF NOT EXISTS FACTURAS(
ID_FACTURA VARCHAR(10) PRIMARY KEY,
ID_CLIENTE VARCHAR(10),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FECHA_EMISION DATE,
TOTAL DECIMAL
);
