DROP DATABASE IF EXISTS TiendaRopa;
CREATE DATABASE IF NOT EXISTS TiendaRopa;
USE TiendaRopa;

CREATE TABLE IF NOT EXISTS ROPA(
CODIGO VARCHAR(10) PRIMARY KEY NOT NULL,
TIPO VARCHAR(20),
TAMAÑO VARCHAR(2) CHECK (TAMAÑO IN('S','M','L','XL')),
COLOR VARCHAR(15),
PRECIO DECIMAL (10,2)
);

INSERT INTO ROPA (CODIGO,TIPO,TAMAÑO,COLOR,PRECIO)
VALUES ('31231','CHANDAL','M','AZUL', 12.99);

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR(50),
TELEFONO VARCHAR(15),
EMAIL VARCHAR(50)
);

INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, TELEFONO, EMAIL)
VALUES ('12313','PEPE','63535434','CARRILO@GMAIL.COM');

CREATE TABLE IF NOT EXISTS VENTAS(
ID_VENTAS VARCHAR(10) PRIMARY KEY,
ID_CLIENTE VARCHAR(10),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
TOTAL DECIMAL
);

INSERT INTO VENTAS (ID_VENTAS,ID_CLIENTE,TOTAL)
VALUES ('CAMISETA','12313',20.21);

CREATE TABLE IF NOT EXISTS DETALLES_VENTA(
ID_VENTAS VARCHAR(10),
FOREIGN KEY (ID_VENTAS) REFERENCES VENTAS (ID_VENTAS),
ID_CLIENTE VARCHAR(10),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
FECHA_EMISION DATE,
TOTAL DECIMAL
);

INSERT INTO DETALLES_VENTA (ID_VENTAS,ID_CLIENTE,FECHA_EMISION,TOTAL)
VALUES ('CAMISETA','12313','2025-10-04', 20.90);

CREATE TABLE IF NOT EXISTS FACTURAS(
ID_FACTURAS VARCHAR (10) PRIMARY KEY,
ID_CLIENTE VARCHAR(10),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
FECHA_EMISION DATE,
TOTAL DECIMAL
);

INSERT INTO FACTURAS (ID_FACTURAS,ID_CLIENTE,FECHA_EMISION,TOTAL)
VALUES ('212313123','12313','2025-10-04', 25.90);

